### ISSUE TITLE
Running two local bots causing init errors

### ISSUE THREAD

**Issue by raspersc2** [aiarena/aiarena-client-gui#50]
**Describe the bug**
Running two simple Python bots against each other (basic bot vs loser bot), both game windows open and load, but then the windows unexpectedly close at the start of the game. I've had the same bug with basic bots downloaded from ai-arena too.

**To Reproduce**
1. Set up a game between basic bot and loser bot
2. Wait for the game windows to open ,load then close again
3. Check the `stderr` file in one of the bot's directory

**Expected behavior**
Game should play out as normal

**Desktop (please complete the following information):**
 - Windows 10
 - Version 0.2.4

**Additional context**

**Stderr log**
```
Traceback (most recent call last):
  File "D:\LMGUI\Bots\basic_bot\sc2\protocol.py", line 41, in __request
    response_bytes = await self._ws.receive_bytes()
  File "C:\Users\Tom\anaconda3\lib\site-packages\aiohttp\client_ws.py", line 281, in receive_bytes
    raise TypeError(
TypeError: Received message 257:None is not bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\LMGUI\Bots\basic_bot\__init__.py", line 76, in join_ladder_game
    result = await sc2.main._play_game(players[0], client, realtime, portconfig, step_time_limit, game_time_limit)
  File "D:\LMGUI\Bots\basic_bot\sc2\main.py", line 223, in _play_game
    result = await _play_game_ai(client, player_id, player.ai, realtime, step_time_limit, game_time_limit)
  File "D:\LMGUI\Bots\basic_bot\sc2\main.py", line 135, in _play_game_ai
    proto_game_info = await client._execute(game_info=sc_pb.RequestGameInfo())
  File "D:\LMGUI\Bots\basic_bot\sc2\protocol.py", line 65, in _execute
    response = await self.__request(request)
  File "D:\LMGUI\Bots\basic_bot\sc2\protocol.py", line 46, in __request
    sys.exit(2)
SystemExit: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 17, in <module>
    result, opponentid = run_ladder_game(bot)
  File "D:\LMGUI\Bots\basic_bot\__init__.py", line 67, in run_ladder_game
    result = asyncio.get_event_loop().run_until_complete(g)
  File "C:\Users\Tom\anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "D:\LMGUI\Bots\basic_bot\__init__.py", line 81, in join_ladder_game
    except ConnectionAlreadyClosed:
NameError: name 'ConnectionAlreadyClosed' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 30, in <module>
    f.write(str(exc_type)+" "+fname+" "+ exc_tb.tb_lineno)
TypeError: can only concatenate str (not "int") to str
```

**Comment by danielvschoor** [comment]
Caused by max game time being set to 00:00:00. #63 opened to address this pitfall
